PredicacionPorTelefono/Controllers/CongregacionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PredicacionPorTelefono.Models;

namespace PredicacionPorTelefono.Controllers
{
    public class CongregacionController : Controller
    {
        private DB_9EB27B_TJEntities db = new DB_9EB27B_TJEntities();

        // GET: Congragacions
        public async Task<ActionResult> Index()
        {
            return View(await db.Congragacions.ToListAsync());
        }

        // GET: Congragacions/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Congragacion congragacion = await db.Congragacions.FindAsync(id);
            if (congragacion == null)
            {
                return HttpNotFound();
            }
            return View(congragacion);
        }

        // GET: Congragacions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Congragacions/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Nombre,Usuario,Password,Direccion,Circuito")] Congragacion congragacion)
        {
            if (ModelState.IsValid)
            {
                db.Congragacions.Add(congragacion);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(congragacion);
        }

        // GET: Congragacions/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Congragacion congragacion = await db.Congragacions.FindAsync(id);
            if (congragacion == null)
            {
                return HttpNotFound();
            }
            return View(congragacion);
        }

        // POST: Congragacions/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Nombre,Usuario,Password,Direccion,Circuito")] Congragacion congragacion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(congragacion).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(congragacion);
        }

        // GET: Congragacions/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Congragacion congragacion = await db.Congragacions.FindAsync(id);
            if (congragacion == null)
            {
                return HttpNotFound();
            }
            return View(congragacion);
        }

        // POST: Congragacions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Congragacion congragacion = await db.Congragacions.FindAsync(id);
            db.Congragacions.Remove(congragacion);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PredicacionPorTelefono/Controllers/TerritoriosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PredicacionPorTelefono.Models;

namespace PredicacionPorTelefono.Controllers
{
    public class TerritoriosController : Controller
    {
        private DB_9EB27B_TJEntities db = new DB_9EB27B_TJEntities();

        // GET: Territorios
        public async Task<ActionResult> Index()
        {
            var territorios = db.Territorios.Include(t => t.Congragacion);
            return View(await territorios.ToListAsync());
        }

        // GET: Territorios/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Territorio territorio = await db.Territorios.FindAsync(id);
            //Actualización: Jose Liza - 2018/06/17
            var territorios = db.Territorios.Where(c => c.CongregacionId == id);
            //
            if (territorios == null)
            {
                return HttpNotFound();
            }
            return View("Index", await territorios.ToListAsync());
        }

        // GET: Territorios/Create
        public ActionResult Create()
        {
            ViewBag.CongregacionId = new SelectList(db.Congragacions, "Id", "Nombre");
            return View();
        }

        // POST: Territorios/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,CongregacionId,Territorio1,Mapa,CoordenadaX,CoordenadaY")] Territorio territorio)
        {
            if (ModelState.IsValid)
            {
                db.Territorios.Add(territorio);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CongregacionId = new SelectList(db.Congragacions, "Id", "Nombre", territorio.CongregacionId);
            return View(territorio);
        }

        // GET: Territorios/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Territorio territorio = await db.Territorios.FindAsync(id);
            if (territorio == null)
            {
                return HttpNotFound();
            }
            ViewBag.CongregacionId = new SelectList(db.Congragacions, "Id", "Nombre", territorio.CongregacionId);
            return View(territorio);
        }

        // POST: Territorios/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,CongregacionId,Territorio1,Mapa,CoordenadaX,CoordenadaY")] Territorio territorio)
        {
            if (ModelState.IsValid)
            {
                db.Entry(territorio).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CongregacionId = new SelectList(db.Congragacions, "Id", "Nombre", territorio.CongregacionId);
            return View(territorio);
        }

        // GET: Territorios/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Territorio territorio = await db.Territorios.FindAsync(id);
            if (territorio == null)
            {
                return HttpNotFound();
            }
            return View(territorio);
        }

        // POST: Territorios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Territorio territorio = await db.Territorios.FindAsync(id);
            db.Territorios.Remove(territorio);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PredicacionPorTelefono/Views/Congregacion/Create.cshtml
@model PredicacionPorTelefono.Models.Congragacion

@{
    ViewBag.Title = "Nuevo Registro";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Congragación</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Usuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Usuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Usuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Circuito, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Circuito, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Circuito, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Ir a la Lista", "Index")
</div>

PredicacionPorTelefono/Views/Congregacion/Delete.cshtml
@model PredicacionPorTelefono.Models.Congragacion

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Congragacion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Circuito)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Circuito)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PredicacionPorTelefono/Views/Congregacion/Details.cshtml
@model PredicacionPorTelefono.Models.Congragacion

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Congragacion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Circuito)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Circuito)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PredicacionPorTelefono/Views/Congregacion/Edit.cshtml
@model PredicacionPorTelefono.Models.Congragacion

@{
    ViewBag.Title = "Nuevo Registro";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Congragacion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Usuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Usuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Usuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Circuito, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Circuito, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Circuito, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Ir a la Lista", "Index")
</div>

PredicacionPorTelefono/Views/Congregacion/Index.cshtml
@model IEnumerable<PredicacionPorTelefono.Models.Congragacion>

@{
    ViewBag.Title = "Congregaciones";
}

@Html.ActionLink("Nuevo", "Create", new { id = 1 }, new { @class = "btn btn-success ad-click-event" })

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.Usuario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Direccion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Circuito)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.Usuario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Password)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Circuito)
            </td>
            <td>
                <a href="@Url.Action("Details", "Territorios", new { id = item.Id})" , class="btn btn-info btn-sm"><span>Territorios</span></a>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }, new { @class = "btn btn-primary btn-sm" })
                @Html.ActionLink("Borrar", "Delete", new { id = item.Id }, new { @class = "btn btn-danger btn-sm" })
            </td>
        </tr>
    }

</table>