PredicacionPorTelefono/Models/Territorio.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PredicacionPorTelefono.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Territorio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Territorio()
        {
            this.Casas = new HashSet<Casa>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CongregacionId { get; set; }
        public string Territorio1 { get; set; }
        public string Mapa { get; set; }
        public Nullable<decimal> CoordenadaX { get; set; }
        public Nullable<decimal> CoordenadaY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Casa> Casas { get; set; }
        public virtual Congragacion Congragacion { get; set; }
    }
}

PredicacionPorTelefono/Controllers/CasasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PredicacionPorTelefono.Models;

namespace PredicacionPorTelefono.Controllers
{
    public class CasasController : Controller
    {
        private DB_9EB27B_TJEntities db = new DB_9EB27B_TJEntities();

        // GET: Casas
        public async Task<ActionResult> Index()
        {
            var casas = db.Casas.Include(c => c.Territorio);
            return View(await casas.ToListAsync());
        }

        // GET: Casas/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Casa casa = await db.Casas.FindAsync(id);
            //Actualización: Jose Liza - 2018/06/17
            var casas = db.Casas.Where(c => c.TerritorioId==id);
            //
            if (casas == null)
            {
                return HttpNotFound();
            }
            return View("Index", await casas.ToListAsync());
        }

        // GET: Casas/Create
        public ActionResult Create()
        {
            ViewBag.TerritorioId = new SelectList(db.Territorios, "Id", "Territorio1");
            return View();
        }

        // POST: Casas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,TerritorioId,Tipo,Calle,Numero,DepInt,Telefono1,Telefono2,Telefono3,Abonado,Distrito,Observaciones")] Casa casa)
        {
            if (ModelState.IsValid)
            {
                db.Casas.Add(casa);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.TerritorioId = new SelectList(db.Territorios, "Id", "Territorio1", casa.TerritorioId);
            return View(casa);
        }

        // GET: Casas/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Casa casa = await db.Casas.FindAsync(id);
            if (casa == null)
            {
                return HttpNotFound();
            }
            ViewBag.TerritorioId = new SelectList(db.Territorios, "Id", "Territorio1", casa.TerritorioId);
            return View(casa);
        }

        // POST: Casas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,TerritorioId,Tipo,Calle,Numero,DepInt,Telefono1,Telefono2,Telefono3,Abonado,Distrito,Observaciones")] Casa casa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(casa).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.TerritorioId = new SelectList(db.Territorios, "Id", "Territorio1", casa.TerritorioId);
            return View(casa);
        }

        // GET: Casas/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Casa casa = await db.Casas.FindAsync(id);
            if (casa == null)
            {
                return HttpNotFound();
            }
            return View(casa);
        }

        // GET: Casas/Notas/5
        public async Task<ActionResult> Notas(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Casa casa = await db.Casas.FindAsync(id);
            if (casa == null)
            {
                return HttpNotFound();
            }
            ViewBag.TerritorioId = new SelectList(db.Territorios, "Id", "Territorio1", casa.TerritorioId);
            return View(casa);
        }

        // POST: Casas/Notas/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Notas([Bind(Include = "Id,TerritorioId,Tipo,Calle,Numero,DepInt,Telefono1,Telefono2,Telefono3,Abonado,Distrito,Observaciones")] Casa casa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(casa).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.TerritorioId = new SelectList(db.Territorios, "Id", "Territorio1", casa.TerritorioId);
            return View(casa);
        }
        
        // POST: Casas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Casa casa = await db.Casas.FindAsync(id);
            db.Casas.Remove(casa);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PredicacionPorTelefono/Controllers/TerritoriosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PredicacionPorTelefono.Models;

namespace PredicacionPorTelefono.Controllers
{
    public class TerritoriosController : Controller
    {
        private DB_9EB27B_TJEntities db = new DB_9EB27B_TJEntities();

        // GET: Territorios
        public async Task<ActionResult> Index()
        {
            var territorios = db.Territorios.Include(t => t.Congragacion);
            return View(await territorios.ToListAsync());
        }

        // GET: Territorios/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Territorio territorio = await db.Territorios.FindAsync(id);
            //Actualización: Jose Liza - 2018/06/17
            var territorios = db.Territorios.Where(c => c.CongregacionId == id);
            //
            if (territorios == null)
            {
                return HttpNotFound();
            }
            return View("Index", await territorios.ToListAsync());
        }

        // GET: Territorios/Create
        public ActionResult Create()
        {
            ViewBag.CongregacionId = new SelectList(db.Congragacions, "Id", "Nombre");
            return View();
        }

        // POST: Territorios/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,CongregacionId,Territorio1,Mapa,CoordenadaX,CoordenadaY")] Territorio territorio)
        {
            if (ModelState.IsValid)
            {
                db.Territorios.Add(territorio);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CongregacionId = new SelectList(db.Congragacions, "Id", "Nombre", territorio.CongregacionId);
            return View(territorio);
        }

        // GET: Territorios/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Territorio territorio = await db.Territorios.FindAsync(id);
            if (territorio == null)
            {
                return HttpNotFound();
            }
            ViewBag.CongregacionId = new SelectList(db.Congragacions, "Id", "Nombre", territorio.CongregacionId);
            return View(territorio);
        }

        // POST: Territorios/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,CongregacionId,Territorio1,Mapa,CoordenadaX,CoordenadaY")] Territorio territorio)
        {
            if (ModelState.IsValid)
            {
                db.Entry(territorio).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CongregacionId = new SelectList(db.Congragacions, "Id", "Nombre", territorio.CongregacionId);
            return View(territorio);
        }

        // GET: Territorios/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Territorio territorio = await db.Territorios.FindAsync(id);
            if (territorio == null)
            {
                return HttpNotFound();
            }
            return View(territorio);
        }

        // POST: Territorios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Territorio territorio = await db.Territorios.FindAsync(id);
            db.Territorios.Remove(territorio);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PredicacionPorTelefono/Views/Territorios/Create.cshtml
@model PredicacionPorTelefono.Models.Territorio

@{
    ViewBag.Title = "Nuevo Registro";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Territorio</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CongregacionId, "Congregacion", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CongregacionId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CongregacionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Territorio1">Nombre del Territorio</label>
            @*@Html.LabelFor(model => model.Territorio1, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.EditorFor(model => model.Territorio1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Territorio1, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Mapa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mapa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mapa, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.CoordenadaX, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CoordenadaX, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CoordenadaX, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CoordenadaY, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CoordenadaY, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CoordenadaY, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Ir a la Lista", "Index")
</div>

PredicacionPorTelefono/Views/Territorios/Delete.cshtml
@model PredicacionPorTelefono.Models.Territorio

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Territorio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Territorio1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Territorio1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mapa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mapa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoordenadaX)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoordenadaX)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoordenadaY)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoordenadaY)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Congragacion.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Congragacion.Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PredicacionPorTelefono/Views/Territorios/Details.cshtml
@model PredicacionPorTelefono.Models.Territorio

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Territorio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Territorio1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Territorio1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mapa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mapa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoordenadaX)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoordenadaX)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoordenadaY)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoordenadaY)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Congragacion.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Congragacion.Nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PredicacionPorTelefono/Views/Territorios/Edit.cshtml
@model PredicacionPorTelefono.Models.Territorio

@{
    ViewBag.Title = "Nuevo Registro";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Territorio</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CongregacionId, "Congregacion", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CongregacionId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CongregacionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Territorio1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Territorio1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Territorio1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mapa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mapa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mapa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CoordenadaX, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CoordenadaX, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CoordenadaX, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CoordenadaY, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CoordenadaY, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CoordenadaY, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PredicacionPorTelefono/Views/Territorios/Index.cshtml
@model IEnumerable<PredicacionPorTelefono.Models.Territorio>

@{
    ViewBag.Title = "Territorios";
}

@Html.ActionLink("Nuevo", "Create", new { id = 1 }, new { @class = "btn btn-success ad-click-event" })


<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.Territorio1)*@
            Congregación

        </th>
        <th>
                @Html.DisplayNameFor(model => model.Mapa)
            </th>
        @*<th>
                @Html.DisplayNameFor(model => model.CoordenadaX)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CoordenadaY)
            </th>*@
        <th>
            @*@Html.DisplayNameFor(model => model.Congragacion.Nombre)*@
            Territorio
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Congragacion.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Territorio1)
            </td>
            <td>
                <a href="@item.Mapa" class="link-black"><span>Ver Mapa</span></a>
            </td>
            @*    <td>
                    @Html.DisplayFor(modelItem => item.CoordenadaX)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CoordenadaY)
                </td>*@

            <td>
                <a href="@Url.Action("Details", "Casas", new { id = item.Id})" , class="btn btn-info btn-sm"><span>Listar Casas</span></a>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }, new { @class = "btn btn-primary btn-sm" })
                @Html.ActionLink("Borrar", "Delete", new { id = item.Id }, new { @class = "btn btn-danger btn-sm" })
            </td>
        </tr>
    }

</table>